spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true
        default_batch_fetch_size: 100
        open-in-view: false
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  redis:
    host: localhost
    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace
decorator:
  datasource:
    p6spy:
      enable-logging: true
jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  # echo 'swimming-spring-boot-security-jwt-secret-value-create-with-base64-encode-swimming-spring-boot-security-jwt-secret-value-create-with-base64-encode'|base64
  secret: c3dpbW1pbmctc3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXNlY3JldC12YWx1ZS1jcmVhdGUtd2l0aC1iYXNlNjQtZW5jb2RlLXN3aW1taW5nLXNwcmluZy1ib290LXNlY3VyaXR5LWp3dC1zZWNyZXQtdmFsdWUtY3JlYXRlLXdpdGgtYmFzZTY0LWVuY29kZQo=
  token-validity-in-seconds: 600
  refresh-token-validity-in-seconds: 3600
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  override-with-generic-response: false